### ISSUE TITLE
Download NSRDB data for a specific location id

### ISSUE THREAD

**Issue by MajidSKhoshghalb** [NREL/hsds-examples#10]
Hi @MRossol, Could you let me know how to download the NSRDB data for the year of 2018 and the location id of New York City?
Thanks in advance!
Majid

**Comment by MRossol** [comment]
@MajidSKhoshghalb,  Please see our documentation for the NSRDB here:
https://github.com/NREL/hsds-examples/blob/master/datasets/NSRDB.md

It has all of the information you need.
